apiVersion: v1
kind: ConfigMap

metadata:
  name: frontend-config
  namespace: lanchonete

data:

  env.js: |
    window.env = {
      URL_BACKEND: "/api/cardapio",
      URL_API_GATEWAY: "SEU_API_GATEWAY/pedidos"
    };