apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: lanchonete
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kalyo/frontend-lanchonete:v4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-config
          mountPath: /usr/share/nginx/html/script/env.js
          subPath: env.js
      volumes:
      - name: frontend-config
        configMap:
          name: frontend-config